import { db } from "./components/db.js";
import { inputToSpanText } from "./components/utils.js";
import { setAspectRatioToSvg } from "./components/utils.js";
import { handleFormSubmit } from "./components/utils.js";
import { laminates } from "./components/laminates.js";
inputToSpanText();
setAspectRatioToSvg();
handleFormSubmit();
// laminates();
console.log(db);
